# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set working directory in the container
WORKDIR /dash_app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

# Make port 8050 available to the world outside this container
EXPOSE 8050

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Run the application when the container launches
CMD ["python", "dash_app.py"]