name: rgt-portal
services:
  redis:
    container_name: redis
    image: redis:7.4.2
    ports:
      - 6380:6379
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD:-changeme}"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - rgt-portal-network
  db:
    container_name: postgres
    image: postgres:17.4
    restart: always
    ports:
      - 5500:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_NAME:-app_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rgt-portal-network

  traefik:
    image: traefik:v2.9
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    networks:
      - rgt-portal-network
  backend:
    container_name: backend
    build:
      context: ./backend/
    restart: unless-stopped
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--spider', 'localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rgt-portal-network

  client:
    container_name: frontend
    build:
      context: ./client/
      args:
        - VITE_NODE_ENV=${VITE_NODE_ENV}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_BASE_URL=${VITE_BASE_URL}
    restart: unless-stopped
    ports:
      - 3000:80
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_NODE_ENV: ${VITE_NODE_ENV:-production}
      VITE_BASE_URL: ${VITE_BASE_URL}
      VITE_API_URL: ${VITE_API_URL}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(rgtportal.gotdns.ch)'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--spider', 'http://localhost']
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - rgt-portal-network

  ai:
    container_name: ai
    build:
      context: ./ai/
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - rgt-portal-network

volumes:
  postgres_data:
    name: rgt_postgres_data
  redis_data:
    name: rgt_redis_data

networks:
  rgt-portal-network:
    name: rgt-portal-network
    driver: bridge
