name: rgt-portal
services:
  redis:
    container_name: redis
    image: redis:7.4.2
    ports:
      - 6380:6379
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD:-changeme}"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - rgt-portal-network
  db:
    container_name: postgres
    image: postgres:17.4
    restart: always
    ports:
      - 5500:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_NAME:-app_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rgt-portal-network

  backend:
    container_name: backend
    build:
      context: ./backend/
    restart: unless-stopped
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - rgt-portal-network

volumes:
  postgres_data:
    name: rgt_postgres_data
  redis_data:
    name: rgt_redis_data

networks:
  rgt-portal-network:
    name: rgt-portal-network
    driver: bridge
