import { DataSourceOptions } from "typeorm";
import dotenv from "dotenv";
import {
  AttendanceRecord,
  Department,
  Employee,
  Event,
  EventParticipant,
  Poll,
  PollOption,
  PollVote,
  Post,
  Project,
  ProjectAssignment,
  PtoRequest,
  Role,
  User,
  PostLike,
  PostReaction,
  PostComment,
  EmployeeRecognition,
  Recruitment,
  EmergencyContact,
  ApiKey,
  NotificationPreference,
  Notification,
  CommentReply,
  CommentLike,
  JobMatchResult,
} from "../entities";

dotenv.config();

export const databaseConfig: DataSourceOptions = {
  type: "postgres",
  host: process.env.DB_HOST || "localhost",
  port: parseInt(process.env.DB_PORT || "5432"),
  username: process.env.DB_USERNAME || "postgres",
  password: process.env.DB_PASSWORD || "postgres",
  database: process.env.DB_NAME || "rgt_portal",
  entities: [
    User,
    Role,
    Employee,
    AttendanceRecord,
    Post,
    Project,
    ProjectAssignment,
    Event,
    EventParticipant,
    PtoRequest,
    Department,
    PostLike,
    PostReaction,
    PostComment,
    EmployeeRecognition,
    Poll,
    PollOption,
    PollVote,
    Recruitment,
    EmergencyContact,
    ApiKey,
    Notification,
    NotificationPreference,
    CommentReply,
    CommentLike,
    JobMatchResult,
  ],
  migrations: ["src/migrations/**/*.ts"],
  synchronize: process.env.NODE_ENV !== "development",   
  // synchronize: true,
  // logging: process.env.NODE_ENV !== "production",
};
