name: Build and deploy rgt-portal

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install and build in backend directory
        working-directory: ./backend
        run: |
          npm install
          npm run build

      # Create startup script in backend directory
      - name: Create startup script
        working-directory: ./backend
        run: |
          echo "#!/bin/bash" > startup.sh
          echo "cd /home/site/wwwroot" >> startup.sh
          echo "npm install --only=production" >> startup.sh
          echo "npm start" >> startup.sh
          chmod +x startup.sh

      - name: Zip backend directory for deployment
        working-directory: ./backend
        run: zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37BE093F7B9D44C7A4E16CE9DADE1DB3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2963F6B2A6F340F4BB959300919E7151 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F91C7506D40442F7ACC0A36EE6E6B47B }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "rgt-portal"
          slot-name: "Production"
          package: .
          startup-command: ./startup.sh
